### PR TITLE
Trying to fix alert slider for op7

### PR DESCRIPTION
**Pull request by Ashwin4RC**

### CODE REVIEW

**Comment by luk1337** [comment]
That shouldn't be needed.

**Comment by Ashwin4RC** [comment]
It doesn't start unless it is.
Still its broken[Even when it starts]

**Comment by Ashwin4RC** [comment]
https://del.dog/etifoqowah.pl
Couldn't find anything else

**Comment by luk1337** [comment]
That makes no sense whatsoever. This is not an `oneshot` service.

What if you log that:
```
diff --git a/tri-state-key/main.cpp b/tri-state-key/main.cpp
index daab294..4571b4c 100644
--- a/tri-state-key/main.cpp
+++ b/tri-state-key/main.cpp
@@ -75,6 +75,8 @@ int main() {
         int err;
         struct input_event event {};
 
+        LOG(ERROR) << "action=" << uevent.action << " name=" << uevent.name << " state=" << uevent.state;
+
         if (uevent.action != "change" || uevent.name != "soc:tri_state_key") {
             return;
         }
```

**Comment by Ashwin4RC** [comment]
06-28 08:49:24.239   613   613 I tri-state-key_daemon: tri-state-key: errorlog: 
06-28 08:49:24.239   613   613 I tri-state-key_daemon: uevent action= change
06-28 08:49:24.239   613   613 I tri-state-key_daemon: uevent name=
+        LOG(INFO) <<"tri-state-key: errorlog: " << uevent.state;
+       LOG(INFO) << "uevent action= " << uevent.action;
+        LOG(INFO) << "uevent name= " << uevent.name;

**Comment by luk1337** [comment]
Why did you split it in 3 lines...
BTW you know you have to actually use the slider to get some events there?

**Comment by Ashwin4RC** [comment]
I was moving the slider.
And its an old log.

**Comment by luk1337** [comment]
```
diff --git a/tri-state-key/uevent_listener.cpp b/tri-state-key/uevent_listener.cpp
index 46b77c8..626ea38 100644
--- a/tri-state-key/uevent_listener.cpp
+++ b/tri-state-key/uevent_listener.cpp
@@ -34,6 +34,7 @@ static void ParseEvent(const char* msg, Uevent* uevent) {
     uevent->state.clear();
 
     while (*msg) {
+        LOG(ERROR) << "msg=" << msg;
         if (!strncmp(msg, "ACTION=", 7)) {
             msg += 7;
             uevent->action = msg;
```

what about that...?

**Comment by Ashwin4RC** [comment]
https://del.dog/ofatiyisuk.sql

**Pull request closed without merging**
