### PR TITLE
build gps from source & crypto fixes

### PR DESCRIPTION
**Pull request by elginsk8r**

### CODE REVIEW

**Comment by luk1337** [comment]
Does it actually work?
BTW TARGET_HW_DISK_ENCRYPTION changes are kinda useless, we aren't using FDE.

**Comment by elginsk8r** [comment]
The GPS stuff is working. The crypto commits haven't been tested fully.

**Comment by luk1337** [comment]
This is weird cause we reverted gps simply cause it wasn't working, see 29ceb93032568eab29d1970788e233ce394de3a3

**Comment by luk1337** [comment]
And your HAL is exactly the same as one that was reverted.

**Comment by elginsk8r** [comment]
Ah, well I'm using a build of evervolv with GPS built by source and google maps seems to be working just fine along with a few other apps that use GPS. Let this sit for a bit and I'll test it extensivly through the day

**Comment by luk1337** [comment]
I assume you actually regenerated the vendor makefiles...?

**Comment by elginsk8r** [comment]
Yes I did, there is a pull request for that as well.

**Comment by luk1337** [comment]
Uh I just tried it myself and my GPS is dead now. Not a single sat shows up in gps test app.
Do I really need to build libcurl? Cause that was like the only diff with revert.

**Comment by elginsk8r** [comment]
Hmm, yeah I didn't test with the GPS test app and I'm seeing similar results as you. I must have not set location to GPS only when initially testing. Disregard the pull request for now, unless you want to pick the gptutils patch

**Pull request closed without merging**
